version: '3.5'

services:

  db:
    image: postgres:10.5
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=mypassword
    # volumes:
    #   - './db/init:/docker-entrypoint-initdb.d/'

  flask-api:
    container_name: flask-app
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "db"
    environment:
      - FLASK_ENV=development

  client:
    container_name: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - "flask-api"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://flask-app:5000
