"""initial

Revision ID: 79cfbc35eb7c
Revises: b2b55a039340
Create Date: 2020-03-01 12:02:14.525191

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '79cfbc35eb7c'
down_revision = 'b2b55a039340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logout', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logout')
    # ### end Alembic commands ###
